#services:
#  app:
#    build:
#      context: ../
#      dockerfile: Dockerfile
#
#    ports:
#        - "9090"
#    depends_on:
#        - database
#    environment:
#        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ergasiamod3
#        SPRING_DATASOURCE_USERNAME: postgre
#        SPRING_DATASOURCE_PASSWORD: secret
#  database:
#    image: 'postgres:14.10'
#    ports:
#      - '5432:5432'
#    environment:
#      - 'POSTGRES_USER=postgres'
#      - 'POSTGRES_DB=ergasiamod3'
#      - 'POSTGRES_PASSWORD=secret'
#
version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/ergasiamod3
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret
  database:
    image: 'postgres:14.10'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ergasiamod3
      POSTGRES_PASSWORD: secret
